name: Test CI/CD pipeline
on:
  push:
    branches:
      - main
      - 'feature/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone to improve relevancy of sonar reporting
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      - name: docker-login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
      - name: docker-build
        run:
          docker build -t github-actions-test:v1 .
      - name: docker-tag
        run:
          docker tag github-actions-test:v1 kokriszti/github-actions-test:v1
      - name: docker-push
        run:
          docker push kokriszti/github-actions-test:v1



          
      