name: Test CI/CD pipeline
on:
  push:
    branches:
      - main
      - 'feature/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
jobs:
  supposed-to-fail:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: step-should-fail
        run: |
          echo "This job is supposed to fail but workflow run should still be successful."
          dksjfhkd
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone to improve relevancy of sonar reporting
          fetch-depth: 0
          path: outer-folder/inner-folder
      - name: Print path
        run: |
          pwd
          ls -la
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd outer-folder/inner-folder
          mvn -B package
      - name: define-next-version
        id: define-next-version
        run: |
          chmod +x .github/script/tag_script.sh
          ./.github/script/tag_script.sh
        shell: bash
      - name: docker-login
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_USER: ${{secrets.DOCKER_USER}}
        run:
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
      - name: docker-build
        run:
          docker build --build-arg JAR_PATH=target -t github-actions-test:${{ steps.define-next-version.outputs.NEXT_VERSION }} .
      - name: docker-tag
        run: |
          echo "The next tag is: ${{ steps.define-next-version.outputs.NEXT_VERSION }}"
          docker tag github-actions-test:${{ steps.define-next-version.outputs.NEXT_VERSION }} kokriszti/github-actions-test:${{ steps.define-next-version.outputs.NEXT_VERSION }}
      - name: docker-push
        run:
          docker push kokriszti/github-actions-test:${{ steps.define-next-version.outputs.NEXT_VERSION }}




          
      