name: Test continue-on-error property
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  success_1:
    runs-on: ubuntu-latest
    steps:
      - name: Print line
        run: echo "success"
  success_2:
    runs-on: ubuntu-latest
    steps:
      - name: Print line
        run: echo "success"
  success_3:
    runs-on: ubuntu-latest
    steps:
      - name: Print line
        run: fghfg
  success_4:
    needs: [ success_1,success_2,success_3 ]
    if: always() && (needs.success_1.result == 'success' || needssuccess_2.result == 'success' || needs.success_3.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Print line
        run: echo "success"