name: Test manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Environment to run the tests on'
        required: true
        type: choice
        options:
          - DEV
          - INT
      checkbox-test:
        description: "Run second step"
        type: boolean

jobs:
  echo:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.stage == 'DEV' }}
    steps:
      - name: echo it works
        id: echo-it-works
        run: |
          echo "manually triggered workflow works"
        shell: bash
      - name: conditional step
        id: conditional-step
        if: ${{ inputs.checkbox-test}}
        run: |
          echo "Checkbox was ticked, running conditional step "
        shell: bash
  job-for-INT:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.stage == 'INT' }}
    steps:
      - name: echo it works
        id: echo-it-works
        run: |
          echo "triggered for int"
        shell: bash
