name: Test continue-on-error property
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Environment to run the tests on'
        required: true
        type: choice
        options:
          - DEV
          - INT
          - PROD

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Just to have a step
        run: |
          echo "job1 test1"
  execute-flyway:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0-
      - name: replace with sed
        run: |
          cd kubernetes
          cat flyway.txt
          echo "Using tag manual for deployment"
          sed -i 's/%APP%/myapp-backend/g' flyway.txt
          sed -i 's/%TAG%/manual/g' flyway.txt
          sed -i 's/%STAGE%/dev/g' flyway.txt
          cat flyway.txt
      - name: Apply - dev
        if: always() && ${{ github.event.inputs.stage == 'DEV' }}
        run: |
          echo "Deploying to dev..."
      - name: Apply - int
        if: always() && ${{ github.event.inputs.stage == 'INT' }}
        run: |
          echo "Deploying to int..."
      - name: Appy to cluster - prod
        if: always() && ${{ github.event.inputs.stage == 'PROD' }}
        run: |
          echo "Deploying to prod..."